# Generated by Django 5.0.7 on 2024-07-27 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_remove_booking_user'),
        ('users', '0004_profilemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='users.usermodel'),
        ),
    ]
