# Generated by Django 5.0.7 on 2024-07-27 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_booking_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
    ]
